version: "3.8"
services:
    web:
        build: .
        ports:
            - "8080:8000"
        volumes:
            - logvolume01:/var/log
        links:
            - redis
        
    redis:
        image: redis
        container_name: redis_db
        restart: always
        expose: 
            - "6379"
        ports:
            - "6379:6379"

    mongo:
        image: mongo:latest
        container_name: mongo_db
        volumes:
            - ./mongod.conf:/etc/mongod.conf
            - ./logs:/var/log/mongodb/
            - ./db:/var/lib/mongodb
        env_file:
            - .env
        restart: always
        ports:
            - "27017:27017"
        command: mongod --config /etc/mongod.conf

volumes:
    logvolume01: {}
    db-data:
    mongo-config: